version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: projeto-ifsp-mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - dados-mysql:/var/lib/mysql
  mongo:
    image: mongo:5.0
    container_name: projeto-ifsp-mongo
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - dados-mongo:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  api:
    build: .
    depends_on:
      - mysql
      - mongo
    container_name: projeto-ifsp-api
    ports:
      - ${API_PORT}:3333
    volumes:
      - .:/api
      - /api/node_modules

volumes:
  dados-mysql:
  dados-mongo:
